#!/usr/bin/python

"""
Useful for decoding entries made from dns-responder
"""

import logging, sys
from binascii import unhexlify
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import *

try:
    log = sys.argv[1]
    ln = int(sys.argv[2])
except:
    print 'Usage:\ndns-decoder <log file> <line number>\n'

with open(log, 'r') as iFile:
    hits = iFile.read().splitlines()

hexInput = hits[ln].split(':')[2]
hexStr = unhexlify(hexInput.replace(' ', ''))
print [Ether(hexStr)]
