#!/usr/bin/python

"""
Useful for decoding SQL entries made from dns-checker
"""

import logging, sys
import sqlite3 as lite
from binascii import unhexlify
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import *

try:
    count = sys.argv[1]
except:
    print 'Usage:\ndns-decoder <pkt num>\n'
    sys.exit(1)

con = lite.connect('checker.sqlite')
con.text_factory = str
db = con.cursor()
q = db.execute('SELECT\
                    `pkt`\
                FROM\
                    `packets`\
                WHERE\
                    `num` = "{0}"'.format(count))
hexPkt = q.fetchone()[0]
hexStr = unhexlify(hexPkt.replace(' ', ''))
print [Ether(hexStr)]
