#!/usr/bin/python

"""
Useful for decoding entries made from dns-responder
"""

import logging, sys
from binascii import unhexlify
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import *

with open('query.log', 'r') as iFile:
    hits = iFile.read().splitlines()

line = int(sys.argv[1])
hexInput = hits[line].split(':')[2]
hexStr = unhexlify(hexInput.replace(' ', ''))
print [Ether(hexStr)]
