#!/usr/bin/env python

# Send an email via python

import getpass, smtplib
from email.header import Header
from email.mime.text import MIMEText
from email.utils import formataddr

## Credz
server = raw_input('SMTP Server?\n')
sender = raw_input('\nUsername?\n')
dName = raw_input('\nDisplay Name? (default is username)\n')
rName = raw_input('\nReply to email? (enter for none)\n')
recipients = raw_input('\nSend to whom? (use commas for multiple recipients)\n')
recipients = [to for to in recipients.split(',')]
subject = raw_input('\nSubject?\n')
body = raw_input('\nBody?\n')
password = getpass.getpass('\nPassword? ')

## Server Details
s = smtplib.SMTP(server + ':587')
s.set_debuglevel(1)
s.starttls()
s.login(sender, password)
msg = MIMEText(body)
msg.set_type('text/html')
msg['Subject'] = subject
if not dName:
        dName = sender
msg['From'] = formataddr((str(Header(dName)), sender))
msg['To'] = ", ".join(recipients)
if rName:
        msg['reply-to'] = rName
s.sendmail(sender, recipients, msg.as_string())

