#!/usr/bin/env python

## Filename: qtip [Query 'teh IRC Parser]
## Concept:  Parse the database from qti and do something with it...
## Usage:    ./qtip
## Author:   stryngs

import os
import re
import sqlite3 as lite
import sys

## Open db and begin work
con = lite.connect('irc-logs.sqlite')
db = con.cursor()

## Import TLDs
with open ('TLDs', 'r') as tldFile:
	tldList = []
	for line in tldFile:
		tldList.append(line)

## Sort TLDs
tldList = sorted(tldList)

## Rip domain info
with open ('tmp.lst', 'w') as tFile:
	with con:
		db.execute("SELECT whois FROM irc_join;")
		lcount = 1
		while True:
			row = db.fetchone()
			if row == None:
				break
			row = str(row[0]).split('@')[1].strip().lower()
			dcount = 1
			for tld in tldList:
				tld = tld.strip()
				###print 'Whois Info: ', [row]
				###print [tld]
				###print 'SQL Row Count: %s' % lcount
				###print 'TLD Count: %s' % dcount
				###print 'TLD: %s' % tld
				###print ''
				tld = '\.' + tld + '$'
				tldMatch = re.search(tld, row)
				if tldMatch:
					dot = row.split('.')
					domain = dot[-2]
					tld = dot[-1]
					tgt = '%s.%s' % (domain,tld)
					print 'SQL Row Count: %s' % lcount
					print tgt
					print ''
					tFile.write(dot[-2] + '.' + dot[-1] + "\n")
				dcount += 1
			lcount += 1

## Strip out empty line and cleanup
file('target.lst', "w").write(file('tmp.lst').read().strip())
lines = open('target.lst', 'r').readlines()
lines_set = set(lines)
with open('target.lst', 'w') as out:
	for line in lines_set:
		out.write(line)
os.remove('tmp.lst')
print 'Finished!'
print 'Filename: target.lst'
print ''
sys.exit(0)
