#!/usr/bin/env python

## Filename: cdig
## Concept:  Compare old and new target domain lists for dig-em to prevent duplicate scanning
## Usage:    ./cdig
## Author:   stryngs

## Create the comparisons to prevent re-digging
oFile = raw_input("List of domains previously scanned?\n")
nFile = raw_input("List of domains to scan?\n")
tFile = raw_input("Output File? [nTgts.lst]\n")
if not tFile:
	tFile = 'nTgts.lst'

## Create a set of pre-dug
pSet = set()
with open(oFile, 'r') as iFile:
	old = iFile.readlines()
	for i in old:
		pSet.add(i.strip())

## Create a set of new domains
nSet = set()
with open(nFile, 'r') as iFile:
	new = iFile.readlines()
	for i in new:
		nSet.add(i.strip())

## Compare the sets, and remove old from new creating a set of non-dug domains
with open (tFile, 'w') as oFile:
	for i in nSet - pSet:
		oFile.write(i.strip() + '\n')

