#!/usr/bin/env python

## Filename: qtip [Query 'teh IRC Parser]
## Concept:  Parse the database from qti and do something with it...
## Usage:    ./qtip
## Author:   stryngs

import os
import re
import sqlite3 as lite
import sys

## Open db and begin work
con = lite.connect('irc-logs.sqlite')
db = con.cursor()

## Import TLDs
with open ('TLDs', 'r') as tldFile:
	tldList = []
	for line in tldFile:
		line = line.strip()
		line = '\.' + line + '$'
		tldList.append(line)
print '1. TLD import complete'

## Create set of whois info from db
dbSet = set()
with open ('tmp.lst', 'w') as tFile:
	with con:
		db.execute("SELECT whois FROM irc_join;")
		while True:
			row = db.fetchone()
			if row == None:
				break
			row = str(row[0]).split('@')[1].strip().lower()
			dbSet.add(row)
		db.execute("SELECT whois from irc_quit;")
		while True:
			row = db.fetchone()
			if row == None:
				break
			row = str(row[0]).split('@')[1].strip().lower()
			dbSet.add(row)
print '2. dbSet created'

## Convert dbSet to dbList
dbList = []
for row in dbSet:
	dbList.append(row)
print '3. dbList conversion done'
print '4. Starting domain storage'

## Grab domains from dbList
with open ('target.lst', 'w') as tFile:
	for tld in tldList:
		for row in dbList:
			if re.search(tld, row):
				###print 'Domain detected: %s' % row
				tFile.write(row + "\n")
print '5. Domains stored'

## Strip out empty line
file('tmp.lst', 'w').write(file('target.lst').read().strip())

## Convert tmp.lst to just the domain and tld, removing any duplicates
dup = set()
with open('target.lst', 'w') as oFile:
	with open('tmp.lst', 'r') as iFile:
		for line in iFile:
			dot = line.split('.')
			domain = dot[-2]
			tld = dot[-1]
			tgt = '%s.%s' % (domain,tld)
			dup.add(tgt)
	for i in dup:
		oFile.write(i.strip() + "\n")
print '6. Domains parsed'

## Remove final duplicates and cleanup
os.remove('tmp.lst')
lines = open('target.lst', 'r').readlines()
lines_set = set(lines)
l = []
for i in lines_set:
	l.append(i)
l = sorted(l)
with open('tmp.lst', 'w') as oFile:
	for line in l:
		oFile.write(line)
file('target.lst', 'w').write(file('tmp.lst').read().strip())
os.remove('tmp.lst')
print ''
print 'Finished!'
print 'Filename: target.lst'
print ''
sys.exit(0)
